version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: tarasrushchak
      POSTGRES_PASSWORD: root
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
