version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE_DEV: postgres
      POSTGRES_USER_DEV: postgres
      POSTGRES_PASSWORD_DEV: postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
